DatabaseDirectory /var/lib/clamav
Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 1
MaxQueue 4
MaxFileSize 17M
MaxScanSize 17M
StreamMaxLength 17M
ReadTimeout 30
CommandReadTimeout 5
SendBufTimeout 30
ExitOnOOM yes
User clamav
