"""create initial schema

Revision ID: f371a5ab9b0b
Revises:
Create Date: 2026-09-04 01:31:10.306752
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f371a5ab9b0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=12), nullable=False),
    sa.Column('user_role', sa.String(length=40), nullable=True),
    sa.Column('risk_level', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_channel_external_user', 'conversations', ['channel', 'external_user_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_conversations_external_user_id'), 'conversations', ['external_user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('urgency', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.String(length=40), nullable=True),
    sa.Column('issue_type', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trip_id', sa.String(length=120), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_channel'), 'tickets', ['channel'], unique=False)
    op.create_index(op.f('ix_tickets_external_user_id'), 'tickets', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_issue_type'), 'tickets', ['issue_type'], unique=False)
    op.create_index(op.f('ix_tickets_public_id'), 'tickets', ['public_id'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_urgency'), 'tickets', ['urgency'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_language'), 'knowledge_chunks', ['language'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_chunks_language'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_tickets_urgency'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_public_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_issue_type'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_channel'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_conversations_external_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_index('ix_conversation_channel_external_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
